exporters:
  otlp:
    endpoint: https://gateway.otlp.hasura.io:443
    headers:
      Authorization: pat ${env:HASURA_DDN_PAT}

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  # Data sources: traces, metrics, logs
  debug:
    verbosity: detailed

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

connectors:
  spanmetrics:
    exemplars:
      enabled: true
    metrics_flush_interval: 15s
    dimensions:
      - name: http.host
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"

processors:
  batch: {}

  memory_limiter:
    check_interval: 5s
    limit_percentage: 90
    spike_limit_percentage: 50

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

service:
  pipelines:
    logs:
      exporters:
        - loki
        - debug
      processors:
        - batch
      receivers:
        - otlp

    metrics:
      exporters:
        - prometheus
      processors:
        - batch
      receivers:
        - otlp
        - spanmetrics

    traces:
      exporters:
        - otlp
        - otlp/jaeger
        - spanmetrics
      processors:
        - batch
      receivers:
        - otlp
