exporters:
  otlp:
    endpoint: https://gateway.otlp.hasura.io:443
    headers:
      Authorization: pat ${env:HASURA_DDN_PAT}

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  debug: {}

processors:
  batch: {}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
service:
  pipelines:
    logs:
      exporters:
        - otlp
      processors:
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        - debug
      processors:
        - batch
      receivers:
        - otlp
    traces:
      exporters:
        - otlp
        - otlp/jaeger
      processors:
        - batch
      receivers:
        - otlp
