services:
  app_myloki:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.myloki
    environment:
      HASURA_LOG_LEVEL: debug
      CONNECTION_URL: $APP_MYLOKI_CONNECTION_URL
      HASURA_SERVICE_TOKEN_SECRET: $APP_MYLOKI_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MYLOKI_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MYLOKI_OTEL_SERVICE_NAME
      OTEL_METRICS_EXPORTER: prometheus
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "9011"
        target: 8080
