kind: Connector
version: v2
definition:
  name: myprometheus
  subgraph: prometheus
  source: hasura/prometheus:v0.3.2
  context: .
  envMapping:
    CONNECTION_URL:
      fromEnv: PROMETHEUS_MYPROMETHEUS_CONNECTION_URL
    HASURA_SERVICE_TOKEN_SECRET:
      fromEnv: PROMETHEUS_MYPROMETHEUS_HASURA_SERVICE_TOKEN_SECRET
    OTEL_EXPORTER_OTLP_ENDPOINT:
      fromEnv: PROMETHEUS_MYPROMETHEUS_OTEL_EXPORTER_OTLP_ENDPOINT
    OTEL_SERVICE_NAME:
      fromEnv: PROMETHEUS_MYPROMETHEUS_OTEL_SERVICE_NAME
